"""empty message

Revision ID: 2f7ac0f25f12
Revises:
Create Date: 2023-05-04 22:58:42.952894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f7ac0f25f12"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bbs_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bbs_user",
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nick_name", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("mobile", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("avatar_url", sa.String(length=256), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("signature", sa.String(length=512), nullable=True),
        sa.Column("gender", sa.Enum("MAN", "WOMAN"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mobile"),
        sa.UniqueConstraint("nick_name"),
    )
    op.create_table(
        "bbs_article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("digest", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("index_image_url", sa.String(length=256), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["bbs_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bbs_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bbs_user_fans",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("followed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["bbs_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["bbs_user.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
    )
    op.create_table(
        "bbs_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["bbs_article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["bbs_comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bbs_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bbs_user_collection",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["bbs_article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bbs_user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "article_id"),
    )
    op.create_table(
        "bbs_comment_like",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["bbs_comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bbs_user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "comment_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bbs_comment_like")
    op.drop_table("bbs_user_collection")
    op.drop_table("bbs_comment")
    op.drop_table("bbs_user_fans")
    op.drop_table("bbs_article")
    op.drop_table("bbs_user")
    op.drop_table("bbs_category")
    # ### end Alembic commands ###
